# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#How to write description:
#Write an awesome description for your new site here. You can edit this
#line in _config.yml. It will appear in your document head meta (for
#Google search results) and in your feed.xml site description.

title: Vijet Muley
email: vmuley@syr.edu
description: >- # this means to ignore newlines until "baseurl:"
  Hey there! Vijet here (They pronounce my name like 'Widget'). I am a graduate student at Syracuse University majoring in Applied Data Science. I love databases, data engineering and data warehousing.
  That being said, I also love soccer and racing! Feel free to have an insight in what I do...
baseurl: "/vijetmuley" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: VijetMuley
github_username:  vijetmuley

# Build settings
markdown: kramdown
theme: minima

#Change starts here:
plainwhite:
  name: Vijet Muley
  sitemap: true
  show_excerpts: true
  social_links:
    linkedIn: in/vijetmuley
  navigation:
    - title: About
      url: /vijetmuley/about
    - title: Resume
      url: /vijetmuley/resume
    - title: Publication
      url: /vijetmuley/publication
theme: jekyll-theme-midnight

#Ends here
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - gemfile.lock
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
